### ISSUE TITLE
Allow to install the latest version

### ISSUE THREAD

**Issue by eliecharra** [wbeuil/dctlenv#14]
It could be great to have a `dctlenv install-latest` or `dctlenv upgrade` or `dctlenv use latest` to automatically download, install and use latest available version 😉

**Comment by wbeuil** [comment]
Let's go for `dctlenv install | use latest` !

**Comment by wbeuil** [comment]
Please update dctlenv to 0.1.2 with `git pull` which added the keyword `latest` to install and use commands.
