### ISSUE TITLE
Make version param more flexible

### ISSUE THREAD

**Issue by eliecharra** [wbeuil/dctlenv#16]
It could be cool that both `v0.4.0` and `0.4.0` can work as version input with dctlenv.

With something like this you can normalize every version number : 

* `echo "v0.4.0" | sed -s 's/^v//'` => 0.4.0
* `echo "0.4.0" | sed -s 's/^v//'` => 0.4.0

Actually we got a message which is pretty confusing as version number are inconsistent: 

![image](https://user-images.githubusercontent.com/6154987/110308378-53d8bb00-8000-11eb-89f8-4a192a3293b8.png)

![image](https://user-images.githubusercontent.com/6154987/110308408-5b985f80-8000-11eb-99a6-a8231c5d53fc.png)

**Comment by wbeuil** [comment]
Good idea, I will add it

**Comment by wbeuil** [comment]
Done in the last tag v0.1.3
